import {
  SiPython,
  SiJavascript,
  SiPhp,
  SiSqlite,
  SiDart,
  SiFlutter,
  SiFlask,
  SiBootstrap,
  SiOpencv,
  SiMysql,
  SiGit,
  SiGithub,
  SiAndroidstudio,
  SiPandas,
  SiScikitlearn,
  SiNodedotjs,
  SiTensorflow,
  SiFirebase,
  SiNumpy,
} from "react-icons/si";
import { VscVscode } from "react-icons/vsc";
import { FaChartLine } from "react-icons/fa";

export const iconMap: Record<string, React.ReactNode> = {
  Python: <SiPython />,
  JavaScript: <SiJavascript />,
  PHP: <SiPhp />,
  SQL: <SiSqlite />,
  Dart: <SiDart />,
  Flutter: <SiFlutter />,
  Flask: <SiFlask />,
  Bootstrap: <SiBootstrap />,
  OpenCV: <SiOpencv />,
  Pandas: <SiPandas />,
  Matplotlib: <FaChartLine />,
  "Scikit-Learn": <SiScikitlearn />,
  NumPy: <SiNumpy />,
  MySQL: <SiMysql />,
  Git: <SiGit />,
  GitHub: <SiGithub />,
  "VS Code": <VscVscode />,
  "Android Studio": <SiAndroidstudio />,
  "Node.js": <SiNodedotjs />,
  TensorFlow: <SiTensorflow />,
  Firebase: <SiFirebase />,
};
